services:
  postgres:
    image: 'postgres:latest'
    container_name: sistema-de-qualificacao-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - '5432:5432'